### ISSUE TITLE
Frontend design

### ISSUE THREAD

**Issue by MaxBelitsky** [Zenulous/Texcellence#41]

**Comment by nntdoan** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/wMzLYsF97co" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by nntdoan** [comment]
Here's my idea:
[Link to prototype](https://youtu.be/wMzLYsF97co)
